### PR TITLE
adding image caption, description, and image caption

### PR DESCRIPTION
**Pull request by aastrong**

### CODE REVIEW

**Comment by aastrong** [comment]
@DaveBagler Can you take a peek at my change - simply using a TPL now - using Bootstrap modal markup - has all fields now as well - there are 2 other PR's that are related that im linking you on.

**Comment by DaveBagler** [comment]
@aastrong  is this now using the new field on the file entity, not the image caption module?  Also if so which PR includes the change to the image file entity.

**Comment by aastrong** [comment]
@DaveBagler yes, let me point you to that.

**Comment by aastrong** [comment]
https://github.com/CityofOttawa/ott_core_content_types/pull/65

**Comment by DaveBagler** [comment]
Great, thanks!

**Pull request merged**
