### PR TITLE
brand new content type for gallery

### PR DESCRIPTION
**Pull request by aastrong**

### CODE REVIEW

**Comment by aastrong** [comment]
for https://github.com/CityofOttawa/ottawa_profile/issues/379

**Comment by vhinic** [comment]
Looks good so far, but I need to see this working before we merge it.

**Comment by aastrong** [comment]
sounds good, lets plan a time to review all the new content types once again,

**Comment by DaveBagler** [comment]
I changed the base for this PR from <code>master</code> to <code>7.x-3.x</code>.

**Comment by DaveBagler** [comment]
Merging as this module is not included in the 2.x branch of the install profile and it's no longer going into master but 7.x-3.x.

**Pull request merged**
